version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pyflakes
    versions:
    - 2.2.0
    - 2.3.0
  - dependency-name: pytz
    versions:
    - "2020.5"
